language: go

go:
  - "1.10.3"
  - master  # find out if a upcoming change in Go is going to break us

matrix:
  # We only want to fail the build based on stable versions of Go
  allow_failures:
    - go: master

script:
  - go test
